apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: backend-config
build:
  googleCloudBuild:
    projectId: 'yuwenma-gke-playground' # {"type":"string","x-kustomize":{"setter":{"name":"project_id","value":"yuwenma-gke-playground"}}}
  artifacts:
  - image: 'gcr.io/yuwenma-gke-playground/demo-backend' # {"type":"string","x-kustomize":{"setter":{"name":"gcr_img_1","value":"gcr.io/yuwenma-gke-playground/demo-backend"}}}
deploy:
  kustomize:
    paths: ["./config/base/redis-master", "./config/base/redis-slave"]
