apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: backend-config
build:
  googleCloudBuild:
    projectId: '[PROJECT_ID]' # {"type":"string","x-kustomize":{"setter":{"name":"project_id","value":"[PROJECT_ID]"}}}
  artifacts:
    - image: '[GCR_IMG_1]' # {"type":"string","x-kustomize":{"setter":{"name":"gcr_img_1","value":"[GCR_IMG_1]"}}}
deploy:
  kubectl:
    manifests:
      - config/base/redis-*/deployment.yaml
      - config/base/redis-*/service.yaml